<#macro patientDataDescription>
<div class="introText-c4j">
<b>Provide the data describing your patients by means of a tabular dataset (i.e. CSV, TSV - UTF-8-encoded text file).</b><br/>
Each row of the Patient Data file should characterize a single patient by specifying, in different columns, the <i>patient_id</i>, <i>patient_birth_date</i> 
and, optionally, the <i>patient_gender</i> and <i>other patient facets</i> that you would like to use to stratify patients. 
After uploading the Patient Data file you will interactively define the type of patient-related information specified by each columns.<br/>

<b><a href="https://github.com/fra82/comorbidity4j/raw/master/example/input/comorbidity4j_example_dataset.tar.gz" target="_blank">Download the example dataset</a></b> 
(generated by <a href="https://github.com/synthetichealth/synthea" target="_blank">Synthea</a>), including a 
<a href="https://raw.githubusercontent.com/fra82/comorbidity4j/master/example/input/patients_comorbidity4j_example.csv" target="_blank">patients tabular file</a>.

<!-- Expandable explanation -->
<div class="explainInput">
    <div class="headerExpander">
    	<span>Click for more info</span>
    </div>
    <div class="contentExpander">
	  Columns of the Patient Data file:
	  <ul>
		<li><i>patient_id</i>: (mandatory) ID that unambiguously identifies the patient (any non-empty String can be used)</li>
		<li><i>patient_birth_date</i>: (mandatory) Birth date of the patient (the format of date will be automatically parsed while importing data)</li>
		<li><i>patient_gender</i>: (optional) Gender of the patient (any set non-empty String can be used - at least two different value to characterize female and male patients should be present)</li>
		<li><i>patient_facet_1</i>: (optional) arbitrary feature (set of strings / nominal values) useful to characterize patients (any set of non-empty String can be used - e.g.: each patient can be characterized as: DIABETIC, NOT_DIABETIC, UNKNOWN)</li>
	  </ul>
	  
	  The Patient data file can include an arbitrary number of columns, provided that the previous set of mandatory columns is present.<br/><br/>
	
	  Patient age (<i>patient_birth_date</i>), gender (<i>patient_gender</i>) and the arbitrary patient feature (<i>patient_facet_1</i>) can be exploited in subsequent steps of the comorbidity analysis 
	  so as to filter / stratify patient population in order to execute scoped analyses. 
	  Some examples of arbitrary patient features (<i>patient_facet_1</i> column) includes size of the family (SMALL, MEDIUM, LARGE), ethnicity (ASIAN, AMERICAN, etc.), level of education (ELEMENTARY, HIGH, etc.).<br/><br/>
	  
	  Example of Patient data file format:<br/>
	
<div class="codespan">
<pre>
"patient_id"    "patient_birth_date"    "patient_gender"    "patient_facet_1"
"261"           "22-07-1947"            "F"                 "DIABETIC"
"823"           "01-02-1930"            "M"                 "NOT_DIABETIC"
"911"           "12-12-1980"            "M"                 "NOT_DIABETIC"
</pre>
</div>

    </div>
</div>

</div>

</#macro>


<#macro visitDataDescription>
<div class="introText-c4j">
<b>Provide the data describing the visits of your patients by means of a tabular dataset (i.e. CSV, TSV - UTF-8-encoded text file).</b><br/> 
Each row of the Visit Data file should characterize a single visit of a patient by specifying, in different columns, the <i>patient_id</i>, 
the <i>visit_id</i> and the <i>visit_date</i>. 
After uploading the Visit Data file you will interactively define the type of patient-related information specified by each columns.<br/>

<b><a href="https://github.com/fra82/comorbidity4j/raw/master/example/input/comorbidity4j_example_dataset.tar.gz" target="_blank">Download the example dataset</a></b> 
(generated by <a href="https://github.com/synthetichealth/synthea" target="_blank">Synthea</a>), including a 
<a href="https://raw.githubusercontent.com/fra82/comorbidity4j/master/example/input/visits_comorbidity4j_example.csv" target="_blank">visits tabular file</a>.

<!-- Expandable explanation -->
<div class="explainInput">
    <div class="headerExpander">
    	<span>Click for more info</span>
    </div>
    <div class="contentExpander">
	  Columns of the Visit Data file:
	  <ul>
		<li><i>patient_id</i>: (mandatory) ID that unambiguously identifies the patient (any non-empty String can be used)</li>
		<li><i>visit_id</i>: (mandatory) ID that unambiguously identifies the visit / admission (any non-empty String can be used)</li>
		<li><i>visit_date</i>: (mandatory) Visit date (format interactively specified by the user)</li>
	  </ul>
	  
	  The Visit data file can include an arbitrary number of columns, provided that the previous set of mandatory columns is present.<br/><br/>
	  
	  Example of Visit data file format:<br/>
	
<div class="codespan">
<pre>
"patient_id"    "visit_id"  "visit_date"
"261"           "52244"     "12-03-2014"
"823"           "61004"     "21-09-2011"
"911"           "69054"     "12-12-2006"
</pre>
</div>


    </div>
</div>

</div>

</#macro>


<#macro diagnosisDataDescription>
<div class="introText-c4j">
<b>Provide the data describing the diagnoses spotted for each patient in the context of a specific visit by means of a tabular dataset (i.e. CSV, TSV - UTF-8-encoded text file).</b><br/> 
Each row of the Diagnosis Data file should describe the association of a diagnosis (by a diagnosis code - i.e. ICD9, SNOMED-CT, CUI or any other diagnosisidentifier) to a specific patient 
in a specific visit. These three parameters are provided by specifying, in different columns, the <i>patient_id</i>, the <i>visit_id</i> and the <i>diagnosis_code</i>. 
After uploading the Diagnosis Data file you will interactively define the type of patient-related information specified by each columns.<br/>

<b><a href="https://github.com/fra82/comorbidity4j/raw/master/example/input/comorbidity4j_example_dataset.tar.gz" target="_blank">Download the example dataset</a></b> 
(generated by <a href="https://github.com/synthetichealth/synthea" target="_blank">Synthea</a>), including a 
<a href="https://raw.githubusercontent.com/fra82/comorbidity4j/master/example/input/diagnoses_comorbidity4j_example.csv" target="_blank">diagnoses tabular file</a>.

<!-- Expandable explanation -->
<div class="explainInput">
    <div class="headerExpander">
    	<span>Click for more info</span>
    </div>
    <div class="contentExpander">
	  Columns:
	  <ul>
		<li><i>patient_id</i>: (mandatory) ID that unambiguously identifies the patient (any non-empty String can be used)</li>
		<li><i>visit_id</i>: (mandatory) ID that unambiguously identifies the visit / admission (any non-empty String can be used)</li>
		<li><i>diagnosis_code</i>: (mandatory) ID that unambiguously identifies the disease / diagnosis related to the visit (any non-empty String can be used - i.e. ICD9, SNOMED-CT, CUI or any other identifier)</li>
	  </ul>
	  
	  The Visit Diagnosis data file can include an arbitrary number of columns, provided that the previous set of mandatory columns is present.<br/><br/>
	  
	  Example of Diagnosis data file format:<br/>
	
<div class="codespan">
<pre>
"patient_id"    "admission_id"  "diagnosis_code"
"261"           "52244"         "C0260421"
"823"           "61004"         "C0015695"
"911"           "69054"         "C0015695"
</pre>
</div>


    </div>
</div>

</div>
</#macro>



<#macro descrDiagnosisDataDescription>
<div class="introText-c4j">
<b>Provide a textual description / human-understandable explanation of all or part of the diagnosis codes mentioned in your dataset. 
Such information can be uploaded by a Diagnosis Description a tabular dataset (i.e. CSV, TSV - UTF-8-encoded text file).</b><br/>
The Diagnosis Description file specifies the extended free-text description of all (or a subset of) the diagnosis codes used to reference the diagnoses of your patients. 
Each row of the Diagnosis Description file provides the free text description of a specific diagnosis code by means respectively of the <i>diagnosis_code</i> and the <i>diagnosis_description</i> columns. 
After uploading the Diagnosis Description file you will interactively define the type of patient-related information specified by each columns.<br/>

<b><a href="https://github.com/fra82/comorbidity4j/raw/master/example/input/comorbidity4j_example_dataset.tar.gz" target="_blank">Download the example dataset</a></b> 
(generated by <a href="https://github.com/synthetichealth/synthea" target="_blank">Synthea</a>), including a 
<a href="https://raw.githubusercontent.com/fra82/comorbidity4j/master/example/input/diagnosis_descriptions_comorbidity4j_example.csv" target="_blank">diagnosis descriptions tabular file</a>.

<!-- Expandable explanation -->
<div class="explainInput">
    <div class="headerExpander">
    	<span>Click for more info</span>
    </div>
    <div class="contentExpander">
Each diagnosis of your patients is referenced by means of a diagnosis code (i.e. ICD9, SNOMED-CT, CUI or any other diagnosisidentifier) specified by means of the Diagnosis data file. 
Sometimes the semantics of these diagnosis codes is difficult to grasp. As a consequence, by providing a Diagnosis Description file it is possible to associate a short textual description 
to each or part of the diagnosis codes used in your dataset: this description will be used to generate interactive visulaizations of comorbidities.<br/>
Remember that if a Diagnosis Description file is not provided, in the interactive visulaizations of comorbidities, each diagnosis will be referenced by its unique identifier (diagnosis code) specified by the 
Diagnosis data file: this fact could make it difficult to desume the semantics of the disease in the conmorbidity analysis results. 
It is possible to specify a description of only a subset of the diseases (diagnoses) specified by the Diagnosis data file.<br/>
	  
	  Columns:
	  <ul>
		<li><i>diagnosis_code</i>: (mandatory) ID that unambiguously identifies the disease / diagnosis related to the visit (any non-empty String can be used - i.e. ICD9, SNOMED-CT, CUI or any other identifier)</li>
	    <li><i>diagnosis_description</i>: (mandatory) string that provides a textual description of the diagnosis code.</li>
	  </ul>
	  
	  The Diagnosis Description data file can include an arbitrary number of columns, provided that the previous set of mandatory columns is present.<br/><br/>
	  
	  Example of Diagnosis Description data file format:<br/>
	
<div class="codespan">
<pre>
"diagnosis_code"    "diagnosis_description"
"C0149654"          "Conduct disorder"
"C0080274"          "Retention of urine"
</pre>
</div>


    </div>
</div>

</div>
</#macro>



<#macro diagnosisGroupingDescription>
<div class="introText-c4j">
<b>Join multiple diagnoses into a group of diagnoses, thus considering all these diagnoses as a single one in the analysis of comorbidities.</b><br/>
Grouping diagnosis codes could be useful to merge diagnosis that should be treated as a single one when executing comorbidity analysis. 
For instance, in this way it is possible to easily merge all the diagnosis related to different types of skin cancers into a single diagnosis named "Skin cancers".
</div>
</#macro>


<#macro diagnosisPairingDescription>
<div class="introText-c4j">
<b>Define diagnosis pairing patterns to specify / select the pairs of diagnosis to study for comorbidity.</b>
<div style="margin-left: 15px;">
ATTENTION: if you will not define any diagnosis pairing pattern all pairs of diseases in your dataset will be analyzed to look for relevant comorbidities as 
default behaviour. The execution time of comorbidity analysis and the RAM required is proportional to the number of diagnosis pairs that will be analyzed.<br/>
We suggest to keep this number under 300,000 diagnosis pairs in order to to speed up the computation time and RAM requirements of comorbidity4j. See below to check the actual number of your analysis.
</div>


<div class="explainInput">
    <div class="headerExpander">
    	<span>Click for more info</span>
    </div>
    <div class="contentExpander">
By default, Comorbidity4j analyzes all the pairs of diadnoses specified in your dataset to look for relevant comorbidities.<br/>
In many practical cases, users need to consider only comorbidities involving a specific set of diagnoses (diseases).<br/>
Here you can interactively specify the pairs of diagnoses you are interested to check for comorbidities by specifying for each group of
diagnoses the set of other diagnoses they will be paired to in comorbidity analysis. This process is referred to as the definition of diagnosis pairing patterns.
    </div>
</div>


</div></b>
</#macro>


<#macro comorbidityAnalysisParametersDescription>
<div class="introText-c4j">
<b>Specify a set of parameters to tune the execution of comorbidity analysis.</b><br/>
</div>
</#macro>


