<#import "utilMacro.ftl" as um>
<#import "descriptionMacro.ftl" as dm>

<@um.pageHeader/>

<@um.printMenu/>
	

<@um.pageContent>
	<div class="main">
	  <h2>Comorbidity4web: interactive comorbidity analysis on the web</h2>
	  Comorbidity4web is a Web-based java tool aimed at enabling the analyses of disease comorbidity in an interactive manner, by means of Web visualizations 
	  (<a href="http://backingdata.org/comorbidity4j/" target="_blank">example of comorbidity analysis result</a>). Comorbidity analysis can be executed:
	  <ul>
	  	<li><b>on-line</b>:&nbsp;by means of the Comorbidity4web, from this web page;</li>
	  	<li><b>locally on your workstation</b>:&nbsp;by means of <b>Comorbidity4j, the Java library that powers Comorbidity4web</b>. To download Comorbidity4j Java library and obtain 
	  	instructions for local execution of comorbidity analyses, access the <a href="https://comorbidity4j.readthedocs.io/" target="_blank">Comorbidity4j documentation</a>. Comorbidity analyses executed by
	  	Comorbidity4j expects the same input data and produce the same set of interactive Web visualizations generated by Comorbidity4web, 
	  	but data are processed and results are stored locally to the user workstation. In this way it si possible to enforce a greater data privacy or to exploit more powerful workstations.</li>
	  </ul>
	  
	  <div style="text-align:center; margin: auto; width: 400px; padding: 10px;">
      	<a href="patientData_1_specifyCSV" class="linkButton-c4j" style="font-size: 130%;">Start comorbidity analysis!</a>
      </div>
	  
	  <br/>
      <h3>How Comorbidity4web works?</h3>
	  
	  Comorbidity4web supports the identification and analysis of significant co-occurrences of diagnoses over large datasets of patient data, 
	  using as input patient demographic information (birth-date together with, optionally gender and secondary patient features like education level, ethnicity, etc.) 
	  and the history of diagnoses of a set of patients over time.  everal statistical  measures to identify relevant pairs of co-occurring diagnoses are computed over 
	  the patients' data provided as by the user, and a variety of interactive graphical representations are provided to visualize and analyze the results.<br/><br/>
      
      <b>The web interface of Comorbidity4web constitutes the gateway to set-up, execute and access the results of comorbidity analyses performed by this tool.</b><br/>
	  In particular, from this Web interface Comorbidity4web users can:
      <ul>
      	<li><b>interactively upload and validate all the clinical data needed to execute the comorbidity analysis</b>. 
      	Input data should be provided by the user by means of a set of tabular datasets (i.e. CSV, TSV - UTF-8-encoded text files) presented in more details below in this page;</li>
      	<li><b>fine tune different parameters to customize the analysis of comorbidities</b>, 
      	like strategies to group and pair diagnoses occurring in the input data	or approaches to filter the results of the analysis;</li>
      	<li><b>execute the analysis and explore the results</b>. To this purpose a set of interactive Web-based visualization are generated on the flight. The results of comorbidity analysis can be also downloaded as a zip file including these data in CSV format and as standalone Web visualizations.</li>
      </ul>
      
      Browse the <a href="https://comorbidity4j.readthedocs.io/" target="_blank">Comorbidity4j documentation</a> for more info.
      
      
      <br/>
      <h3>What input data are required to execute a comorbidity analysis by Comorbidity4web?</h3>
      
      On the column on the left side the different steps to set-up an analysis of comorbidities are listed. They include:
      <ul>
      <li><b>Steps 1 to 4</b>: uploading and validation of user’s input data, provided by means of a set of tabular datasets (i.e. CSV, TSV - UTF-8-encoded text files)</li>
      <li><b>Steps 5 to 7</b>: customization of parameters of the comorbidity analysis</li>
      </ul>
      
      It is possible to
      <b><a href="https://github.com/fra82/comorbidity4j/raw/master/example/input/comorbidity4j_example_dataset.tar.gz" target="_blank">download an example dataset</a></b>
      generated by <a href="https://github.com/synthetichealth/synthea" target="_blank">Synthea</a> to inspect the input tabular files that Comorbidity4web expects as input to execute a comorbidity analysis and try the tool. In particular, considering the steps 1 to 3, 
      the following three tabular datasets (i.e. CSV, TSV - UTF-8-encoded text files) are required in order to execute a comorbidity analysis:
      <ul>
      <li><b>Patient data</b>&nbsp;(step 1): a tabular dataset 
      (<a href="https://raw.githubusercontent.com/fra82/comorbidity4j/master/example/input/patients_comorbidity4j_example.csv" target="_blank">download example file</a>) 
      where each row represents a single patient by specifying, in different columns, 
      the <i>patient_id</i>, <i>patient_birth_date</i> and, optionally, the <i>patient_gender</i> and <i>other patient variables or facets</i> required to stratify patients.</li>
      <li><b>Visit data</b>&nbsp;(step 2): a tabular dataset 
      (<a href="https://raw.githubusercontent.com/fra82/comorbidity4j/master/example/input/visits_comorbidity4j_example.csv" target="_blank">download example file</a>) 
      where each row characterizes a single visit of a patient by specifying, in different columns, 
      the <i>patient_id</i>, the <i>visit_id</i> and the <i>visit_date</i>.</li>
      <li><b>Diagnosis data</b>&nbsp;(step 3): a tabular dataset 
      (<a href="https://raw.githubusercontent.com/fra82/comorbidity4j/master/example/input/diagnoses_comorbidity4j_example.csv" target="_blank">download example file</a>) 
      where each row describes the association of a diagnosis 
      (by a diagnosis code - i.e. ICD9, SNOMED-CT, CUI or any other diagnosis identifier) to a specific patient in a particular visit. 
      These three parameters are provided by specifying, in different columns, the <i>patient_id</i>, the <i>visit_id</i> and the <i>diagnosis_code</i>.</li>
      </ul>
      
      The <b>Diagnosis description</b> tabular dataset (step 4, 
      <a href="https://raw.githubusercontent.com/fra82/comorbidity4j/master/example/input/diagnosis_descriptions_comorbidity4j_example.csv" target="_blank">download example file</a>) 
       is an optional data input, used to provide a free-text description to the diagnosis codes.<br/><br/>
      
      When each tabular dataset is uploaded, the user will be asked to interactively define the semantics of each column of the tables, the formats of dates and other parameters of interest to correctly interpret user’s input data. Different column separators and text delimiters are supported.<br/>

	  More details and examples of these tabular dataset are provided interactively while loading data.<br/><br/>
      
	</div>
</@um.pageContent>
	    

<@um.pageFooter/>
